#主机端口号
server:
  port: 1111
#主机名（可用IP，需另外加配置）
eureka:
  instance:
    #ip-address: 169.254.130.127
    #prefer-ip-address: true
    hostname: localhost
  #指定服务注册中心的位置
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      defaultZone: http://localhost:2222/eureka/
#该server注册中心注册在其它注册中心的 服务实例名
#指定微服务的名称后续在调用的时候只需要使用该名称就可以进行服务的访问
spring:
  application:
    name: hzm-eureka-server